### ISSUE TITLE
Allow opening_hours validation without location data

### ISSUE THREAD

**Issue by PanierAvide** [ypid/opening_hours.js#100]
Could you try to implement a way to check if a given opening_hours value is valid without having to give any location data, or having public/school holidays defined ? This would allow to verify if a given user defined value is syntactically valid. Currently, the errors thrown when constructing the opening_hours object prevents this kind of use.
```
An error occurred during evaluation of the value "We 07:00-18:15; SH off || "on appointment"". Please file a bug report here: https://github.com/ypid/opening_hours.js/issues?state=open. There are no holidays SH defined for country fr and state Bretagne. You can also add them: __repository_url__
```
Cordially.

**Comment by ypid** [comment]
Thats a hint that someone should define the SH for France :smile:

I can implement that in the evening. Probably something like `new new opening_hours('We 12:00-14:00', none, mode);`

**Comment by ypid** [comment]
You can use the [nominatiomTestJSON](https://github.com/ypid/opening_hours.js/blob/master/test.js#L50) for now.

**Comment by PanierAvide** [comment]
Haha, why not :) Thanks for the tip and for implementing this ;)
