### ISSUE TITLE
validation fails if contains more than one : 

### ISSUE THREAD

**Issue by dex2000** [ypid/opening_hours.js#101]
"Mo - Fr: 8:30 Uhr - 18:30 Uhr, Sa: 8:30 - 14:00 Uhr, So: 10:30 - 12:30 Uhr"
gives no output, i.e.:
http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo%20-%20Fr%3A%208%3A30%20Uhr%20-%2018%3A30%20Uhr%2C%20Sa%3A%208%3A30%20-%2014%3A00%20Uhr%2C%20So%3A%2010%3A30%20-%2012%3A30%20Uhr&DATE=1441284120000&lat=48.7769&lon=9.1844&mode=0#

"Mo - Fr: 8:30 Uhr - 18:30 Uhr, Sa 8:30 - 14:00 Uhr, So 10:30 - 12:30 Uhr"
shows me then the warnings

**Comment by dex2000** [comment]
but:
"di-sa: 8:30-18:00; so: 11:30-18:00; mo: geschlossen"

gives me an error, cannot see the difference ...

**Comment by ypid** [comment]
#86 :grimacing:

**Comment by ypid** [comment]
Das Probem is bekannt, nur dessen Lösung ist alles andere als trivial, da das `,` auch als Regeltrenner erlaubt ist und das auftrennen in Regeln relativ früh beim parsen stattfindet. Irgendwann werde ich wohl mal wieder in den sauren Apfel beißen müssen und das Problem irgendwie lösen :smile:
