### ISSUE TITLE
The library is maybe unintentionally influencing the i18next locale

### ISSUE THREAD

**Issue by amenk** [ypid/opening_hours.js#112]
See https://github.com/ypid/opening_hours.js/blob/master/opening_hours.js#L3439

You might not want to globally changing the locale to en by just using this library.

Maybe the locale should not be switched if not specified in the "locale" parameter?

Why might also remove the locale parameter, as the locale can be switched globally.

Another option would be to set and restore the locale always when opening_hours is rendering something.

**Comment by ypid** [comment]
You are right. I am on it.

**Comment by ypid** [comment]
@amenk What do you think? I made the locale parameter "local". Global settings should not be altered permanently.

**Comment by amenk** [comment]
Looks good.
