### ISSUE TITLE
Include js folder in node package

### ISSUE THREAD

**Issue by amenk** [ypid/opening_hours.js#113]
I just spend around 30 minutes debugging to find out that the js folder is not in the package.json and thus not fetched when I do `npm install` (without -dev).

Can't we include https://github.com/ypid/opening_hours.js/blob/master/js/ in the package? Especially the helpers.js is nice to have. Or maybe put it in a different package?
Right now I am downloading the files manually, which is un-pretty.

**Comment by ypid** [comment]
I will think about it. I guess it could make sense to bundle the browser only files http://bower.io/. What do you think?

**Comment by amenk** [comment]
Might be the clean way. But I did not yet start using bower. This whole JS package manager hell is frustrating me a bit :-/
I currently install everything via node and then copy the stuff over via gulp/laravel-elixir...

**Comment by ypid** [comment]
NPM and bower seem to be ok. I just run `make ready-for-hosting` and `make publish-website-on-all-servers` in a clean checkout and the code is in "production". Not sure how gulp would fit in my setup thought.

https://github.com/ypid/opening_hours_map/blob/master/Makefile#L13

**Comment by amenk** [comment]
Don't need gulp in the setup. My suggestion was just to also include the js folder / i.e. make it part of the lib. Might also be interesting for backend-scripting, so not sure if we need to use bower.
Or there should be at least a subfolder "website", so it is clear what does not belong into the lib.

**Comment by ypid** [comment]
You are right. I thought about this again and came to the same conclusion. I will just bundle all the files with NPM, and, if requested, also via bower.

**Comment by amenk** [comment]
I still don't get the JS folder - I think it has to be added to `package.json`?

**Comment by amenk** [comment]
sorry, it is working. Oversaw it...
