### ISSUE TITLE
`11:30:` not detected as error in points in time mode.

### ISSUE THREAD

**Issue by farfromrefug** [ypid/opening_hours.js#114]
I have an error when doing this:
```
new openingHours('Mo 11:30-14:00; Tu-Fr 11:30:14:00,18:30-22:00; Sa-Su 18:30-22:00', _pos);
```
it gives me  (same thing through the evaluation tool)
```
Script Error at Mo 11:30-14:00; Tu-Fr 11:30: <--- (hyphen (-) or open end (+) in time range expected. For working with points in time, the mode for opening_hours.js has to be altered. Maybe wrong tag?)
```

It works if i use mode === 2. Though i think it should still work with mode === 0.
There is no point in time in that expression.

Thanks

**Comment by ypid** [comment]
Thanks for reporting. Looks like a wired bug for mode=2. The error in mode=0 is expected.

**Comment by farfromrefug** [comment]
Can you explain why the error in mode 0? I don't get it

Thanks

**Comment by ypid** [comment]
I think the error given is pretty clear: `Mo 11:30-14:00; Tu-Fr 11:30: <--- (hyphen (-) or open end (+) in time range expected. For working with points in time, the mode for opening_hours.js has to be altered. Maybe wrong tag?` except that it refers to points in time mode. There should be no reason for the trailing colon in `11:30:`.

**Comment by farfromrefug** [comment]
oh shoot i actually did not read the string correctly and missed the error :P
thanks @ypid !
