### ISSUE TITLE
Compare opening hours

### ISSUE THREAD

**Issue by sanderd17** [ypid/opening_hours.js#116]
When two oh strings are different, it can be they still mean the same. Like `Mo 10:00-20:00; We-Fr 10:00-20:00` and `Mo-Fr 10:00-20:00; Tu off`.

I would like to check the equality of those two strings. F.e. when you have a dataset of shops with opening hours, and you want to see if these opening hours match the ones in OSM.

I think testing equality would be the most important, but it could also be nice to get the difference between two opening hours.

Would it be possible to add such a method to the library?

**Comment by ypid** [comment]
Sure that would be possible, checking for equality is actually not hard when doing it for a certain time range (like 5 years) so if the two values evaluate to the same state over this period then they are consider to be the same. Checking for difference is a bit more tricky.
I thought about testing for equality once again but I had not yet found a use case for it. Your use case sounds reasonable.

**Comment by sanderd17** [comment]
Checking for equality would be good enough, there's no real need to get the difference. But what do you mean with the 5-years range? Are you planning to loop over all the closing and opening times?

If a shop opens and closes twice a day, 6 days a week, for 5 years, then it would need to compare 624 array elements to test equality. Won't that be a bit slow and memory heavy?

**Comment by ypid** [comment]
You are right of course. I am open to better suggestions :wink: Something like "static code analysis" comes to my mind but that would be more complex …

**Comment by sanderd17** [comment]
Perhaps the week_stable setting can be used to speed it up. If the opening hours are week-stable, then only one week needs to be compared. If one is week-stable and the other one isn't, then they aren't equal. And if both are week-stable, then some years need to be compared.

However, I guess in reality many opening hours aren't week-stable.

**Comment by ypid** [comment]
That is a good optimization :+1:

> However, I guess in reality many opening hours aren't week-stable.

I agree.

**Comment by ypid** [comment]
Done. :smile:
