### ISSUE TITLE
Provide an input for location and country code

### ISSUE THREAD

**Issue by henningvs** [ypid/opening_hours.js#119]
At the moment I would have to create an virtual Nominatim answer to fill  ```var oh = new opening_hours('We 12:00-14:00', nominatiomJSON, mode);``` with a correct nominatiomJSON.

Ist there a way to create a new object without building an nominatim answer (as I don't use a direct nominatim call)? 

Otherwise I would like to propose (and help) to build an interface for a generic input.

**Comment by ypid** [comment]
I am not quite following. You can pass an empty object if you don’t have a `nominatiomJSON` on hand (note the details in the README). Can you be a bit more specific?

**Comment by henningvs** [comment]
Yes indeed, this is possible, but in this case I probably won't get the correct opening hours or the state of the object.
As I have all the needed information on hand (like lat, lon, country code etc.) I want to provide them when creating a new object. So at the moment the only way I could go is to generate an object which contains those information and I'm looking for a better way. Otherwise it probably should be statet in the readme field I have to generate to get a valid nominatim json.

**Comment by ypid** [comment]
If you have the needed information already you can just pass it in in the Nominatim JSON format? I think this is already good enough. The library is written to check for a valid Nominatim JSON where possible so you can pass an incomplete Nominatim JSON and the lib will complain when there is something missing (maybe future releases will use more information from Nominatim. [Unlikely but possible](https://github.com/ypid/opening_hours.js/issues/115#issuecomment-148916799))

**Comment by ypid** [comment]
I am closing this issue. Feel free to reopen/replay if needed.
