### ISSUE TITLE
Bug in invitation to report an issue

### ISSUE THREAD

**Issue by matkoniecz** [ypid/opening_hours.js#120]
http://openingh.openstreetmap.de/evaluation_tool/ after geolocating to Poland produced 

> An error occurred during evaluation of the value "Mo-Fr 10:00-20:00; PH off". Please file a bug report here: https://github.com/ypid/opening_hours.js/issues?state=open. There are no holidays PH defined for country pl. You can also add them: \_\_repository_url\_\_

in

> Error and warning messages:

box

I think that \_\_repository_url\_\_ was supposed to be replaced by something.

**Comment by ypid** [comment]
> I think that __repository_url__ was supposed to be replaced by something.

I agree. Thanks for reporting.
