### ISSUE TITLE
Improve warning when "PH" is missing.

### ISSUE THREAD

**Issue by matkoniecz** [ypid/opening_hours.js#121]
> Apr-Sep: 07:00-20:00; Oct-Mar: 07:00-18:00

in http://openingh.openstreetmap.de/evaluation_tool/#check

results in following complaint:

> Apr-Sep: 07:00-20:00; Oct-Mar: 07:00-18:00 <--- (There was no PH (public holiday) specified. This is not very explicit. Unfortunately the tag key (e.g. "opening_hours", or "lit") is unknown to opening_hours.js. This warning only applies to the key opening_hours. If your value is for that key than read on. If not you can ignore the following. Please either append a "PH off" rule if the amenity is closed on all public holidays or use something like "Sa,Su,PH 12:00-16:00" to say that on Saturdays, Sundays and on public holidays the amenity is open 12:00-16:00. If you are not certain try to find it out. If you can’t then do not add PH to the value and ignore this warning.)

I have no idea why validator complains about PH. There is no good reason to add special case of PH for objects where PH are not influencing anything. In my case it is impossible to add such rule, as on different public holidays this object has different opening hours.

**Comment by ypid** [comment]
> validator complains about PH without clear reason

I do not agree. This check was added to get the mapper to at least think about the possibility that PH could matter for this oh value. This is of course not always the case but opening_hours are most used for amenities and they almost always have special opening hours for PH so I think the warning by default is ok even when that means that oh values like yours will also produce a warning.

Just rewrite your value to make it explicit.

```
Apr-Sep: Mo-Su,PH 07:00-20:00; Oct-Mar: Mo-Su,PH 07:00-18:00
```

Feature #81.

**Comment by matkoniecz** [comment]
Maybe explicit tagging, in the form of

> Oct-Mar: Mo-Su,PH

may be mentioned in message?

**Comment by ypid** [comment]
I discoursed this in a similar issue https://github.com/ypid/opening_hours.js/issues/85#issuecomment-109563852 (for reference).

The thing with the message is a good idea :+1: but it will make the message even longer :wink:

**Comment by ypid** [comment]
It kind of says this already

> "Sa,Su,PH 12:00-16:00" to say that on Saturdays, Sundays and on public holidays the amenity is open 12:00-16:00. If you are not certain try to find it out. If you can’t then do not add PH to the value and ignore this warning.

But I will add this to the message to make sure … :smile:
