### ISSUE TITLE
Please add the public holidays for Romania

### ISSUE THREAD

**Issue by afita** [ypid/opening_hours.js#123]
Hi. Please add the non-working public holidays for Romania. They can be found on Wikipedia:

English - https://en.wikipedia.org/wiki/Public_holidays_in_Romania#Official_non-working_holidays
Romanian (with link to the laws) - https://ro.wikipedia.org/wiki/S%C4%83rb%C4%83tori_publice_%C3%AEn_Rom%C3%A2nia#Zile_oficiale_de_s.C4.83rb.C4.83toare_.C3.AEn_care_nu_se_lucreaz.C4.83.

**Comment by ypid** [comment]
Seems pretty straight forward. Want to write a patch/PR for it?

**Comment by afita** [comment]
Created: https://github.com/ypid/opening_hours.js/pull/125
