### ISSUE TITLE
How to display a time table?

### ISSUE THREAD

**Issue by pke** [ypid/opening_hours.js#131]
Is there a way to get all the opening times in an array describing the day of the week and the times?

**Comment by ypid** [comment]
Sure the is a way … Give it a try.

**Comment by ypid** [comment]
Closing this issue. Feel free to reopen if you encourage a real problem or if you want to share your solution. Also feel free to add your project to the readme.

**Comment by pke** [comment]
I'll develop a solution and share it here. Just one more question: The iterator returned by the iterator API always goes from `Mo` to `Su` or is it possible that the weekdays are intermixed?

**Comment by ypid** [comment]
@pke Yes. The iterator goes thought all changes. You can use [`date.getDay()`](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay) to check which day of the week you got.
