### ISSUE TITLE
rm --force does not work on OS X

### ISSUE THREAD

**Issue by thomaskonrad** [ypid/opening_hours.js#135]
Hi,

I just noticed that ```make clean``` throws the following error on Mac OS X:

    $ make clean
    rm --force export.*.json
    rm: illegal option -- -
    usage: rm [-f | -i] [-dPRrvW] file ...
           unlink file
    make: *** [osm-tag-data-taginfo-rm] Error 64

This could be solved by simply replacing ```rm --force``` by ```rm -f```. This works both under Linux and Mac OS X.

Thanks
Thomas

**Comment by ypid** [comment]
:grin: I like descriptive command line arguments …

I fixed it. Thanks.

**Comment by thomaskonrad** [comment]
That was fast. Thank you!
