### ISSUE TITLE
npm install does not grab moment-with-langs.min.js

### ISSUE THREAD

**Issue by Trefex** [ypid/opening_hours.js#65]
I did an npm install after checkout the repository and it seems the moment-with-langs.min.js is not pulled.

Do you know how to fix this in your setup ?

**Comment by ypid** [comment]
Thanks for the hint. It seems that the moment library has changed there API and file names in [a recent commit](https://github.com/moment/moment/commit/961faffcf8b60b67310ce0c907aa8c3cb8520d06). I will adopt to the new API later and leave the issue open until it I adopted to the new API level.

**Comment by amenk** [comment]
I think it is enough to change the filename in the include to -locales

**Comment by ypid** [comment]
Can you try this while you are on #90?
