### ISSUE TITLE
missing links in readme

### ISSUE THREAD

**Issue by mkoniecz** [ypid/opening_hours.js#67]
"Please have a look at the [evaluation tool][] which can give you an impression how this library can be used and what it is capable of." - in general, search for []

**Comment by ypid** [comment]
Problem is known. Thanks for opening an issue. It appears that GitHub changed something in there Markdown parser. I hoped it was a bug of this parser that might get fixed. I defined all links at the end of the README.md file. I guess the parser does not accept the definition to be so far away from the use anymore.
