### ISSUE TITLE
Public holidays bug on web

### ISSUE THREAD

**Issue by damjang** [ypid/opening_hours.js#73]
I discover this site and this js and I think that are very good. I go to Italy to check openig_hours but see some errors: e.g. see [this](http://www.openstreetmap.org/way/120139283) have this error:
> An error occurred during evaluation of the value "Tu-Fr 09:30-13:00; Sa,PH 10:00-13:00,15:00-19:00". Please file a bug report here: https://github.com/ypid/opening_hours.js/issues?state=open. No holidays are defined for country it. You can also add them: https://github.com/ypid/opening_hours.js

Ok, correct, country **It** don't have defined PHs. The wrong thing is then if I go to [this](http://www.openstreetmap.org/way/169835990) point in Slovenija the same error appear (No holidays are defined for country it). But if I click to **evaluation tool** for the same point the country evaluated is correct (Si) so no error. The same error I have also in other countries...

**Comment by ypid** [comment]
Thanks for reporting. That has probably to do with the way, the country code are aquired by reverse geocoding. I will look into this when I have time.

**Comment by ypid** [comment]
Bug is in the opening_hours_map. I created an issue there: https://github.com/ypid/opening_hours_map/issues/34
