### ISSUE TITLE
Josm-validator with mysterios warning

### ISSUE THREAD

**Issue by dex2000** [ypid/opening_hours.js#75]
We off, Mo,Tu,Th-Su,PH,Jun-Aug We 11.30-14.00,17:00+
Gives me in Josm the warning:
We off, Mo,Tu,Th-Su,PH, Jun <-- (Unerwartetes Merkmal (Schulfeiertage-Parser): month) (1)

http://openingh.openstreetmap.de/evaluation_tool/?EXP=We%20off%2C%20Mo%2CTu%2CTh-Su%2CPH%2CJun-Aug%20We%2011.30-14.00%2C17%3A00%2B&DATE=1357161660000&lat=48.7769&lon=9.1844&mode=0
says its right.

Dunno wheres the Mistake, any Ideas?

Edit: forgotten some errors in the Tag, but:
We off, Mo,Tu,Th-Su,PH,Jun-Aug We 11:30-14:00,17:00+
same problem...

**Comment by ypid** [comment]
Das ist ein Hinweis, den [`<additional_rule_separator>`](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#additional_rule_separator) nur zu verwenden, wenn er unbedingt sein muss :smile:

[`<additional_rule_separator>`](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#additional_rule_separator) sind überflüssig in diesem Wert. Bei dem Wert muss man ein bisschen aufpassen, da open end und eine `We off` geschrieben wurde …

Ich würde vermuten, das folgendes gemeint war: [Mo-Tu,Th-Su,PH 11:30-14:00,17:00+; Jun-Aug We 11:30-14:00,17:00+`](http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Tu%2CTh-Su%2CPH%2011%3A30-14%3A00%2C17%3A00%2B%3B%20Jun-Aug%20We%2011%3A30-14%3A00%2C17%3A00%2B&DATE=1364934060000&lat=48.7769&lon=9.1844&mode=0)

Das ist aber auch ein Bug in opening_hours.js. Danke fürs berichten.

**Comment by ypid** [comment]
Das eigentliche Problem ist gelöst, es steht allerdings noch deine kleine Überarbeitung an, wegen des [`<additional_rule_separator>`](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#additional_rule_separator) Tokens. Problem ist, dass <additional_rule_separator> das gleiche Zeichen ist, wie das für das Trennen von [Zeiten](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#timespan) usw. Ich hoffe, dass ich das bei Gelegenheit ein für alle mal beheben kann.

**Comment by dex2000** [comment]
"Ich würde vermuten, das folgendes gemeint war: Mo-Tu,Th-Su,PH 11:30-14:00,17:00+, Jun-Aug We 11:30-14:00,17:00+"
Mir qualmt der Kopp. :) Also ja, ich seh aber das Problem immer noch nicht richtig. Es ist nicht vorgesehen Monatsranges zu normalen Tagen zu "addieren"?

Dass We off mit Tu 17:00+ kollidiert hab ich gar nich bemerkt. Wobei man hier die landläufige Meinung in die Berechnung nehmen könnte. (Also "der Tag is vorbei, wenn man ins Bett geht" bzw. "der Tag fängt an, wenn man aufsteht") 
Ok, auch nich der Weisheit letzter Schluss.

**Comment by ypid** [comment]
> Es ist nicht vorgesehen Monatsranges zu normalen Tagen zu "addieren"?

Addieren? Meinst du das `Jun-Aug We` für jeden Tag zwischen Jun und Aug zutreffen sollte und zusätzlich auf jeden Mittwoch?
Das ist nicht vorgesehen. Dafür können zwei Regeln benutzt werden: `Jun-Aug; We`
Wenn es eine Regel ist (`Jun-Aug We`) werden die beiden Bereichsauswähler logisch Und Verknüpft. Sie müssen also beide zutreffen.

Wie schon gesagt ist der Wert etwas speziell wegen dem open end was im Standard in den nächsten Tag rein geht. Wäre es `Mo-Tu,Th-Su,PH 11:30-14:00; Jun-Aug We 11:30-14:00` würde ich das `,` ganz weglassen.

**Comment by ypid** [comment]
Das `We off` hat im Wert `We off, Mo,Tu,Th-Su,PH,Jun-Aug We 11.30-14.00,17:00+` keine Probleme bereitet. Es hat aber auch keinerlei Auswirkung gehabt und kann deshalb weggelassen werden. Zudem war es als `We off,` mit `,` als Regeltrenner, was absolut keinen Sinn macht (#76).

**Comment by dex2000** [comment]
Hui, hab ich mich ma wieder konfus ausgedrückt.
Mit addieren meinte ich das Komma als "und", also in absoluter Kurzfassung: Sonntag UND die Mittwoche im Juni -> "Su, Jun We". -> Fehler. (Su in dem Falle ist, was ich mit "normale Tage" meinte)

Das "We off," is klar falsch, (is aber nich an der Fehlermeldung in josm beteiligt) das hab ich AUCH mal wieder übersehen, herrje, dafür sieht #76 ganz brauchbar aus.

**Comment by ypid** [comment]
Ah, verstehe. Nach [Spezifikation](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#section:rule_separators) ist das tatsächlich erlaubt. Allerdings habe ich es für opening_hours.js [anderes implementiert](https://github.com/ypid/opening_hours.js#features) und jetzt wo ich darüber nach denke macht `Su, Jun We` auch absolut keinen Sinn. Ich habe mir also etwas gedacht damals :smile:. Der Grund ist, dass [`<additional_rule_separator>`](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#additional_rule_separator) so definiert sind, dass die folgende Regel Zeiten addieren kann. Im genannten Beispiel hat die erste Regel aber gar keine Zeiten. Deshalb sollte `Su; Jun We` verwendet werden, was den gleichen Effekt hat.

**Comment by ypid** [comment]
In die Spezifikation hatte ich es auch schon reingeschreiben, allerdings nur unter [Erklärung](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#explain:additional_rule_separator). Ich habe es noch etwas deutlicher gemacht und es kommt jetzt auch eine treffendere Fehlermeldung für [`Su, Jun We`](http://openingh.openstreetmap.de/evaluation_tool/?EXP=Su%2C%20Jun%20We&DATE=1428868800000&lat=48.7769&lon=9.1844&mode=0).

**Comment by dex2000** [comment]
Ok, ich muss nochma nachfragen, ob ich es jetzt verstanden hab ;)
Einfache Wochentage (bspw. Mo,Su und sogar PH usw.) kann man mit Komma separieren, "komplexe" wie "PH Mo", "Jun Mo" sind aber als additional belegt und dürfen auf die herkömmliche Weise nicht zu "einfachen" addiert werden? (Ääh sorry, wenn das hier in ner Art Forendiskussion ausartet, aber:)
Warum ich das bisher nicht verstanden habe: es erscheint mir hochgradig unlogisch - oder zumindest wenig logisch. Auch dein Satz:
"macht Su, Jun We auch absolut keinen Sinn" 
hab ich mir paar Mal durchgelesen und komme nicht weiter. Warum denn nicht? Weils so in der Spec steht? Dann ist imho die Spec kaputt bzw. an der Stelle zu gierig.
"Mo, PH We 17:00+" sieht für mich als Mensch derbst wohlgeformt aus. Das lese ich, und sehe sofort was gemeint ist. (Du hast ja auch das etwas umfangreichere Initialbeispiel zum Problem ganz genau verstanden)
Ich sehe die Notwendigkeit nicht zwischen: "Mo,PH" oder "Mo,Su" "Mo,PH We" einen (technischen) Unterschied zu machen.
Hab ich ein Brett vorm Kopf?

**Comment by ypid** [comment]
Das mag zwar verständlich sein, aber es ist nicht der Sinn von `<additional_rule_separator>` an allen stellen wo `;` benutzt werden kann eingesetzt zu werden. Es wurde ursprünglich nur das `;` definiert. Das `<additional_rule_separator>` gab es erst als es Netzwolf definiert hatte. Das `,` hat an der stelle eine genau definierte Bedeutung: `Regel1, Regel2`. Hier überschreibt Regel2 nicht die Zeiten für die Tage an denen Regel1 und Regel2 zutrifft, sondern addiert die Zeiten. Das ist der einzige Zweck von `<additional_rule_separator>`.

Mir ist es auch schon aufgefallen, dass manche Webseiten ihre Öffnungszeiten mit `,` trennen, aber die Webseiten schreiben ihre Öffnungszeiten halt irgendwie. Bei OSM gibt es dafür eine Syntax und die unterscheidet sich nun mal von dem, was man normalerweise so schreibt und versteht.

`Mo,PH` oder `Mo,Su` ist ok. `Mo,PH We` funktioniert nicht. Das einzige was geht ist [`PH Mo,Th`](http://openingh.openstreetmap.de/evaluation_tool/?EXP=PH%20Mo%2CTh&DATE=1420321380000&lat=48.7769&lon=9.1844&mode=0) was bedeutet, dass ein Geschäft offen hat wenn ein Feiertag auf einen Montag oder einen Donnerstag fällt.

> Einfache Wochentage (bspw. Mo,Su und sogar PH usw.) kann man mit Komma separieren, "komplexe" wie "PH Mo", "Jun Mo" sind aber als additional belegt und dürfen auf die herkömmliche Weise nicht zu "einfachen" addiert werden?

Verstehe ich nicht ganz. Bitte schaue dir die [Spezifikation genauer an](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#time_domain). Da sind solche Fragen beantwortet. Die Erklärungen übersetze ich vermutlich die Woche noch ins Deutsche. Das `,` wirkt wie ein `;` mit dem oben genannten Unterschied. „einfachen“ und „komplexe“ Regeln gibt es im technischen Sinne nicht.

https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#explain:additional_rule_separator
