### ISSUE TITLE
Show warning for `Mo 12:00-14:00; 2014+ off`

### ISSUE THREAD

**Issue by ypid** [ypid/opening_hours.js#77]

**Comment by dex2000** [comment]
Maybe should be useful to get warnings for all values what contain 2014, 2013 and/or lower.

**Comment by ypid** [comment]
Sure, thats what I wanted to express with this. `Mo 12:00-14:00; 2014+ off`is just an example because it is short.

**Comment by ypid** [comment]
`2014+ off` should not throw a warning. I did not think about this enough when opening the issue. Thanks to @dex2000. I implemented a warning for your example.
