### ISSUE TITLE
fix button

### ISSUE THREAD

**Issue by Klumbumbus** [ypid/opening_hours.js#78]
example node: https://www.openstreetmap.org/node/1150742417

with

opening_hours=Th-Su

is reported by JOSM with "This rule is not very explizit...". The fix button is not geyed out. If you hit them the warning message disappears but the opening hours tag did not change. I think the button should be greyed out. 

JOSM status report:

Revision: 8240
Repository Root: http://josm.openstreetmap.de/svn
Relative URL: ^/trunk
Last Changed Author: simon04
Last Changed Date: 2015-04-20 00:15:43 +0200 (Mon, 20 Apr 2015)
Build-Date: 2015-04-20 01:31:09
URL: http://josm.openstreetmap.de/svn/trunk
Repository UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last Changed Rev: 8240

Identification: JOSM/1.5 (8240 en) Windows 7 32-Bit
Memory Usage: 315 MB / 742 MB (138 MB allocated, but free)
Java version: 1.8.0_45, Oracle Corporation, Java HotSpot(TM) Client VM
VM arguments: [-Djava.security.manager, -Djava.security.policy=file:C:\Program Files\Java\jre1.8.0_45\lib\security\javaws.policy, -DtrustProxy=true, -Djnlpx.home=<java.home>\bin, -Djnlpx.origFilenameArg=C:\Program Files\josm-latest-bla.jnlp, -Djnlpx.remove=true, -Djava.util.Arrays.useLegacyMergeSort=true, -Djnlpx.heapsize=256m,768m, -Djnlpx.splashport=57668, -Djnlpx.jvm=<java.home>\bin\javaw.exe, -Djnlpx.vmargs=LURqYXZhLnV0aWwuQXJyYXlzLnVzZUxlZ2FjeU1lcmdlU29ydD10cnVlAA==]
Dataset consistency test: No problems found

**Comment by ypid** [comment]
Thanks for reporting. The problem can not be fixed by opening_hours.js. I opened a ticket for JOSM: https://josm.openstreetmap.de/ticket/11360#ticket
