### ISSUE TITLE
How does <date offset> work?

### ISSUE THREAD

**Issue by daganzdaanda** [ypid/opening_hours.js#82]
Hi there!

I was trying things like these:
```easter -We 10:00-15:00 open```
```Nov 23 -We 10:00-15:00 open```
The second one would describe "Buß- und Bettag", which is always on the Wednesday before the 23rd of November (says Wikipedia).

But the tool throws an error: http://openingh.openstreetmap.de/evaluation_tool/?EXP=Nov%2023%20-We%2010%3A00-15%3A00%20open
It does not change when I add a space between the minus and the <wday>.

So is this syntax correct and the tool just can't validate it yet?
Or did I make a mistake?

**Comment by ypid** [comment]
Hi

Sorry for my late response. Your examples are correct and you are right that the evaluation tool does not handle this yet. See #25. But fortunattly, your example can already be expressed in a different supported way:

[`Nov 16-Nov 22: We open "Buß- und Bettag"`](http://openingh.openstreetmap.de/evaluation_tool/?EXP=Nov%2016-Nov%2022%3A%20We%20open%20%22Bu%C3%9F-%20und%20Bettag%22&DATE=1447804860000&lat=48.7769&lon=9.1844&mode=0)

I am closing this issue in favour to #25.

**Comment by daganzdaanda** [comment]
Thank you for the explanation of #25, I didn't understand that issue when I saw it... 
Also that's a smart alternative for "Buß- und Bettag", thanks!
