### ISSUE TITLE
Bayerische Weihnachtsferien

### ISSUE THREAD

**Issue by daganzdaanda** [ypid/opening_hours.js#83]
Zufällig beim Rumprobieren ist mir aufgefallen, dass die Weihnachtsferien in Bayern einen Tag zu kurz sind. Der 5.1.2015 war ein Ferientag, und der 5.1.2016 wird einer sein, aber bei der Auswertung zählen sie nicht als SH. Ich hab dann die entsprechenden Kalender von schulferien.org angeschaut. Dort ist jeweils der 6.1. als letzter Ferientag drin:

SUMMARY:Weihnachtsferien 2014 Bayern
DTSTART;VALUE=DATE:20141224
DTEND;VALUE=DATE:20150106

SUMMARY:Weihnachtsferien 2015 Bayern
DTSTART;VALUE=DATE:20151224
DTEND;VALUE=DATE:20160106

Ist da bei der Übertragung ein Fehler passiert?

**Comment by ypid** [comment]
Vielen dank für das Bereichten des Fehlers :+1: 

Das Fehler beim übertragen passiert sind, ist unwahrscheinlich, da dieser Prozess weitgehend automatisiert ist :smile: Die Definition ist korrekt nur die Auswertung nicht. Ich habe schon eine Vermutung, wo das Problem liegt.

**Comment by daganzdaanda** [comment]
Ich hatte erst gedacht, es könnte daher kommen, dass diese Ferien ja über die Jahresgrenze gehen. Allerdings wurde dann der 4.1. doch als SH erkannt...

**Comment by ypid** [comment]
Jahresgrenzen habe ich bereits berücksichtigt, aber das Problem hängt mit den Jahresgrenzen zusammen. Es sieht so aus, dass in diesem Fall (SH über Jahresgrenz) immer der letzte Tag von SH fehlt.
