### ISSUE TITLE
do not force PH if no day is given as in "10:00-22:00"

### ISSUE THREAD

**Issue by HolgerJeromin** [ypid/opening_hours.js#85]
Sometimes I have opening_hours for playgrounds or so which are open at any day. So we do no need a day. 
But the new PH detection need it. 
Imo "10:00-22:00" should not be changed to "Mo-Fr, PH 10:00-22:00" to make the validation happy.

**Comment by dex2000** [comment]
get no warning an no nothing for "opening_hours=10:00-22:00" can you give steps to reproduce?

**Comment by HolgerJeromin** [comment]
You tested josm? 
The website has more levels of warnings since  
https://github.com/ypid/opening_hours.js/commit/4d5d4dc8f6569b52f1564fbf72b20ea8539877a4

**Comment by dex2000** [comment]
i have tested josm, josm-latest, the OH-validator-website and the OH-map-website. No Errors, no warnings.

**Comment by HolgerJeromin** [comment]
http://openingh.openstreetmap.de/evaluation_tool/?EXP=10%3A00-20%3A00&DATE=1433418000000&lat=50.7714682&lon=6.03865909576416&mode=0

Gives here

10:00-20:00 <--- (There was no PH (public holiday) specified. This is not very explicit. Unfortunately the tag key (e.g. "opening_hours", or "lit") is unknown to opening_hours.js. This warning only applies to the key opening_hours. If your value is for that key than read on. If not you can ignore the following. Please either append a "PH off" rule if the amenity is closed on all public holidays or use something like "Sa,Su,PH 12:00-16:00" to say that on Saturdays, Sundays and on public holidays the amenity is open 12:00-16:00. If you are not certain try to find it out. If you can’t then do not add PH to the value and ignore this warning.)

**Comment by ypid** [comment]
Hi

After thinking about this now I am of the opinion that the current behavior is most beneficial. Reasons:

* I saw enough opening_hours for facilities which where specified as `08:00-17:00`. Almost all mappers think of this as `Mo-Su 08:00-17:00` and forget about `PH`. The warning would at least get them to think about it. And once they are on the details, maybe there are more exception like in your example maybe winter (Is the playground safe/open in the winter?).
* [Explicit is better than implizite.](http://legacy.python.org/dev/peps/pep-0020/)
* It is not much harder to write `Mo-Su,PH 10:00-22:00` than `10:00-22:00`.
* If I add more exceptions to the "warn for missing PH" check it would make it more difficult for mappers to understand when PH is recommended and when not.

I understand that in the case of a playground or something like that it is a little overhead but as I see it opening_hours are mostly used together with facilities like `amenity=*` and `shop=*`.

Please read #81 for details. If I missed something feel free to reopen this issue …

**Comment by HolgerJeromin** [comment]
I am OK with the decision. :-)
