### ISSUE TITLE
Ability to translate error messages

### ISSUE THREAD

**Issue by amenk** [ypid/opening_hours.js#89]
It should be possible to translate error message (i.e. use i18next)

Example: https://github.com/ypid/opening_hours.js/blob/master/opening_hours.js#L4365

**Comment by amenk** [comment]
Would it be bad to include the i18next package? I think this would break BC because an additional lib has to be included?

**Comment by ypid** [comment]
I was waiting for someone to request this :smile: because I thought about this myself. It would be nice but it has a low priority. It does not necessarily break backwards compatibility. This feature should be implemented as plugin for the opening_hours.js and the core opening_hours.js (which is already quite large) should not depend on those translations or on i18next (using a simple wrapper for the `t` function if not defined) (see also #71). i18next is already used to translate the website. PRs are welcome.

**Comment by amenk** [comment]
I started extracting the strings. I defined a t() function which works similar to i18n

**Comment by ypid** [comment]
Please use different git branches when you are working on new features which might end up in this repo after I merge them:

* https://github.com/iMi-digital/opening_hours.js/commit/6d91e1db075b18dc7f268d2dd442bab01da2f87e
* https://github.com/iMi-digital/opening_hours.js/commit/5957abeaed646abaeb7362a2c5b84a655bfcd3bc

(Two different issues, to different branches :smile: )
You can use git check-pick to fix this.

**Comment by amenk** [comment]
Yes for a PR I will make branches.

**Comment by ypid** [comment]
OK, thanks.

**Comment by amenk** [comment]
so here is a new commit. But I would do #90 in the same branch because it depends on this.

**Comment by ypid** [comment]
Looks nice :+1: OK, sure. You could create a base branch for both of your feature branches but that is not that important to me. What matters is code quality so one branch is probably easier to work with. No problem.

**Comment by amenk** [comment]
Thank you. I am particularly proud of my initialization of i18n and reusing existing instances :) 
https://github.com/iMi-digital/opening_hours.js/commit/a598d7a5264f84019b9fca81696c3b9a677fce10#diff-27c1b5b9334016944e0dd0388f00ce4bR66

wondering if there is an easier way.

**Comment by ypid** [comment]
> wondering if there is an easier way.
Not sure. Looks good.

Can you extend the test framework as needed if one message you are translating/touching is not already in [test.log](https://github.com/ypid/opening_hours.js/blob/master/test.log) most of them should be contained)?

**Comment by amenk** [comment]
hm. dunno ... I totally already exceeded the allocated time on this :) But testing is important I guess.

**Comment by ypid** [comment]
Sorry to hear that …
Should be not to much work as most of the warnings (if not all) should be already contained in the test.log. The corresponding warning can be triggered from test.js under "values which should return a warning".

**Comment by amenk** [comment]
Oh my: https://github.com/ypid/opening_hours.js/blob/master/opening_hours.js#L3845

**Comment by ypid** [comment]
Right … Sorry for that

**Comment by amenk** [comment]
I think I got it translated now. Took only 30 minutes :)

**Comment by amenk** [comment]
Translation is finished. Can you merge?

**Comment by ypid** [comment]
Well done :+1: Just one thing. When I run the test framework it shows a diff for various warnings. `make check-diff-opening_hours.js` could you maybe resolve this please?

**Comment by amenk** [comment]
*updated*. there are some remaining differences where I think I fixed bugs. Can you verify that? Should I then commit my test.log and commit the new test.log ?

**Comment by ypid** [comment]
Thanks very much for the update. There are still some things different which should be equal. Like:

    -Feb 30 <--- (Month Feb either has 28 or 29 days (leap years).)
    +Feb 30 <--- ("Month Feb either has 28 or 29 days (leap years).")

    -easter + 370 days <--- (There should be no reason to differ more than 200 days from a event like easter. If so tell us …)
    +easter + 370 days <--- (max_differ)

Except that, it looks really nice :+1: :+1: 
I am going to commit the new test.log when I review your changes. I will also create a second test.log for your German translations and review them too.

**Comment by amenk** [comment]
More fixes...

**Comment by amenk** [comment]
and: Thanks for the good QA :)
