### ISSUE TITLE
Allow internationalization of value returned by oh.prettifyValue()

### ISSUE THREAD

**Issue by amenk** [ypid/opening_hours.js#90]
The library is also useful for non-OSM-used where the opening times are in a local language.

It would be great if it was possible to translate SH / PH / Weekdays / Monthnamess in a local language by specifying a locale.

**Comment by ypid** [comment]
Already possible, no need to rewrite the input tolerance feature of opening_hours.js :smile:

See https://github.com/ypid/opening_hours.js/blob/e57b1b65dcbf73b88d3b309db9f130722ad706ee/opening_hours.js#L2919

Note that a warning will be generated in case keywords are used not covered by the [spec](https://wiki.openstreetmap.org/w/index.php?title=Key:opening_hours/specification). Just ignore warnings when in non-OSM use cases.

**Comment by amenk** [comment]
Good point. But I would like to have a prettified string also with the German codes... But I might be able to omit that.

**Comment by ypid** [comment]
I am also a native German speaker so German is already quite well supported I think.

[`Montag-Freitag 10:00-20:00; Schulferien,Sonn- und Feiertageoff`](http://openingh.openstreetmap.de/evaluation_tool/?EXP=Montag-Freitag%2010%3A00-20%3A00%3B%20Schulferien%2CSonn-%20und%20Feiertageoff&DATE=1435920180000&lat=48.7769&lon=9.1844&mode=0)

**Comment by amenk** [comment]
I know you are :)
But it does not allow to generate a prettified string in German.
What I could do is to ignore all warnings and then after prettifying replace "We" by "Mi" and so on. That might work but not sure if it is that clean?

**Comment by ypid** [comment]
String replacement is discouraged of course :) For that use case I would recommend to get the tokens array and replace it there. See the demo.html for an example.

**Comment by amenk** [comment]
how exactly? I can't find any example of such in the demo.html

**Comment by ypid** [comment]
Search for `prettified_value_array` in demo.html.

**Comment by amenk** [comment]
But then I have to rebuild the string from the array... duplicating half of prettifyValue() ... hm

**Comment by ypid** [comment]
If you can hack up prettifyValue() to return a nice German representation of the opening hours why not. prettifyValue() can be configured via the `conf` parameter. You can add a new conf option like 'locale' and then include it into opening_hours.js.

**Comment by amenk** [comment]
okay I will try. Could be integrated with the `t()` function I guess

**Comment by ypid** [comment]
Could be integrated with `t()`. But I am not sure if this would be a big advantage because for the translation. It is probably better/simpler to define a hash with all the locales in it something like:

	var prettified_value_locales = {
		'de': {
			'weekday': {
				'mo': 'Montag',
			}
		}
	}

**Comment by amenk** [comment]
But I thought you do not want to increase the size of the `opening_hours.js` so much? Or this hash you suggest could be included in the lang file as well ..

**Comment by ypid** [comment]
The hash `prettified_value_locales` could later be moved to a own JS module.

OK, right. This (i18next) might be better in that case. `suncalc` as an example can also be used by opening_hours.js to have additional features. You can try it with i18next.

**Comment by amenk** [comment]
or we can use moment's i18n ?

**Comment by ypid** [comment]
Right, almost forgot moment’s … Yes, that would be the best option. Maybe #65 should be solved first so that this project can use the current version …

**Comment by amenk** [comment]
Here it is

**Comment by ypid** [comment]
When you are done can you open a PR. I will have a closer look tonight.

**Comment by amenk** [comment]
There are in #89 lots of messages still to be extracted / translated. Would you have time to do this? Or maybe I can find some colleague. I probably will not have time for it.

**Comment by ypid** [comment]
Unfortunately this feature is not very high on my priority list and it is a hobby project. If I get funded I would be more than happy to do it :smile:

**Comment by amenk** [comment]
I think I will do it :-)

**Comment by amenk** [comment]
is finished. Can you merge?
